# No Provision

In this strategy, half of the portfolio is in token zero, and the other half is in token one. The assets will not be deposited in any pool. This simple strategy is a good benchmark because it shows how much the value of the tokens increased. Since no liquidity was provided, there is no impermanent loss of earned fees. This strategy will be our reference strategy, which we will take as a baseline.

Import code dependencies

In [21]:
pd.read_csv("/Users/gnapsamuel/Documents/AMM/demeter-fetch/sample-data/ethereum-0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640-2024-09-01.raw.csv")

      block_number      block_timestamp                                   transaction_hash  transaction_index  log_index                                             topics                                               data
0         20651994  2024-09-01 00:00:11  0x171f5fe7942a6f5c6e5030237787c74bed43d758e3f6...                325        610  ['0xc42079f94a6350d7e6235f29174924f928cc2ac818...  0xffffffffffffffffffffffffffffffffffffffffffff...
1         20651994  2024-09-01 00:00:11  0xa3050bbf94559a991715bfa4464c44d7d20f7854d7dc...                330        627  ['0xc42079f94a6350d7e6235f29174924f928cc2ac818...  0xffffffffffffffffffffffffffffffffffffffffffff...
2         20651995  2024-09-01 00:00:23  0x80fea5d92665ce63d7de445af8fc146a1f4a02107fc3...                 75        159  ['0xc42079f94a6350d7e6235f29174924f928cc2ac818...  0x00000000000000000000000000000000000000000000...
3         20651996  2024-09-01 00:00:35  0x62c0a40ef4e8d9c16d282d3f38d571284c8bf693a04d...                  2         12  ['0xc42079f94a6350d7e6235f29174924f928cc2ac818...  0x00000000000000000000000000000000000000000000...
4         20651996  2024-09-01 00:00:35  0x62c0a40ef4e8d9c16d282d3f38d571284c8bf693a04d...                  2         16  ['0xc42079f94a6350d7e6235f29174924f928cc2ac818...  0x00000000000000000000000000000000000000000000...
...            ...                  ...                                                ...                ...        ...                                                ...                                                ...
5772      20659156  2024-09-01 23:59:47  0xc39ee581380dba78242269aa71a877a739a789162a1f...                  5         41  ['0xc42079f94a6350d7e6235f29174924f928cc2ac818...  0xffffffffffffffffffffffffffffffffffffffffffff...
5773      20659156  2024-09-01 23:59:47  0x85d05884d4a24c7c03ad0cc6764fa4075fb588f9f7f0...                 34        166  ['0xc42079f94a6350d7e6235f29174924f928cc2ac818...  0xffffffffffffffffffffffffffffffffffffffffffff...
5774      20659156  2024-09-01 23:59:47  0x9f8fd8a0b09941764ffb384869c754d6cb5aa7308703...                 42        188  ['0xc42079f94a6350d7e6235f29174924f928cc2ac818...  0xffffffffffffffffffffffffffffffffffffffffffff...
5775      20659157  2024-09-01 23:59:59  0xeb9dc3c002c25ecccae0c5afedfc8cb90cf2d024ed28...                  1         14  ['0xc42079f94a6350d7e6235f29174924f928cc2ac818...  0xffffffffffffffffffffffffffffffffffffffffffff...
5776      20659157  2024-09-01 23:59:59  0x1ea07c51ff7d73859f460d043440759607b18e3638fa...                 78        199  ['0xc42079f94a6350d7e6235f29174924f928cc2ac818...  0xffffffffffffffffffffffffffffffffffffffffffff...

[5777 rows x 7 columns]

In [23]:
pd.read_parquet("/Users/gnapsamuel/Documents/AMM/proteus-LP-backtesting/data/uniswap/USDC-WETH/fee_500/liquidity/liquidity_distribution_20659574.parquet")

           block    tick  active_tick     liquidity        price       amount0       amount1  amount0_real  amount1_real
107948  20659574  198311       192210  6.929849e+17  4496.174045  2.322657e+10  5.168435e+18  23226.567157      5.168435
107949  20659574  198311       192220  6.929849e+17  4491.680343  2.321496e+10  5.171020e+18  23214.958124      5.171020
107950  20659574  198311       192230  6.929849e+17  4487.191132  2.320335e+10  5.173606e+18  23203.354126      5.173606
107951  20659574  198311       192240  6.948413e+17  4482.706408  2.325388e+10  5.190060e+18  23253.884601      5.190060
107952  20659574  198311       192250  7.006928e+17  4478.226166  2.343799e+10  5.236384e+18  23437.992292      5.236384
...          ...     ...          ...           ...          ...           ...           ...           ...           ...
109041  20659574  198311       203140  5.460422e+17  1507.241968  1.059638e+10  7.033825e+18  10596.376965      7.033825
109042  20659574  198311       203150  5.460422e+17  1505.735554  1.059108e+10  7.037343e+18  10591.080366      7.037343
109043  20659574  198311       203160  5.460373e+17  1504.230647  1.058569e+10  7.040799e+18  10585.692193      7.040799
109044  20659574  198311       203170  5.460323e+17  1502.727243  1.058030e+10  7.044256e+18  10580.304369      7.044256
109045  20659574  198311       203180  5.356882e+17  1501.225342  1.037468e+10  6.914265e+18  10374.680989      6.914265

[1098 rows x 9 columns]

In [24]:
pd.read_csv("/Users/gnapsamuel/Documents/AMM/demeter-fetch/sample-data/ethereum-0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640-2024-09-01.minute.csv")

                timestamp    netAmount0            netAmount1  closeTick  openTick  lowestTick  highestTick   inAmount0             inAmount1      currentLiquidity
0     2024-09-01 00:00:00    1205548047   -479406602084206666   198026.0  198026.0    198026.0     198026.0  1208562616      1200000000000000  10799232130943241891
1     2024-09-01 00:01:00 -123047896483  48992196156121041882   198030.0  198026.0    198026.0     198030.0           0  48992196156121041882  10856801167937041729
2     2024-09-01 00:02:00    -304014176    121072457726657916   198030.0  198030.0    198030.0     198030.0           0    121072457726657916  10856801167937041729
3     2024-09-01 00:03:00        570469      -226959741091278   198030.0  198030.0    198030.0     198030.0      570469                     0  10856801167937041729
4     2024-09-01 00:04:00       1136136      -452009252299572   198030.0  198030.0    198030.0     198030.0     1136136                     0  10856801167937041729
...                   ...           ...                   ...        ...       ...         ...          ...         ...                   ...                   ...
1435  2024-09-01 23:55:00  -59061833023  24326228262941489530   198368.0  198368.0    198368.0     198368.0   249229666  24428793897185918976   7402815832990292073
1436  2024-09-01 23:56:00   -9739999822   4012630605307956513   198369.0  198369.0    198369.0     198369.0   500505848   4218615258425416139   7402815832990292073
1437  2024-09-01 23:57:00      67160433    -27615019757024137   198369.0  198369.0    198369.0     198369.0   127884720     25016230242975863   7402815832990292073
1438  2024-09-01 23:58:00   -8848874262   3645523684140990313   198369.0  198369.0    198369.0     198369.0    40950000   3662376745840664692   7402815832990292073
1439  2024-09-01 23:59:00  -95921758889  39529131280587499898   198375.0  198369.0    198369.0     198375.0           0  39529131280587499898   7045724782223933636

[1440 rows x 10 columns]

In [1]:
from datetime import date, datetime
import pandas as pd

from demeter import TokenInfo, Actuator, Strategy, RowData, ChainType, MarketInfo, AtTimeTrigger
from demeter.result import performance_metrics
from demeter.uniswap import UniV3Pool, UniLpMarket

Set pandas output format

In [2]:
pd.options.display.max_columns = None
pd.set_option("display.width", 5000)

Custom No Provision strategy with nothing in work function.

In [9]:
# the time should be a variable we choose 
# synced with the data we load 
class NoProvisionStrategy(Strategy):
    def initialize(self):
        """
        Initialize function will be called right before a backtest start.
        You can do various things here, e.g. register a trigger, or add a simple moving average line.
        """
        new_trigger = AtTimeTrigger(  # define a new trigger
            #this date should be synced or as a variable so you don't have to change it here 
            time=datetime(2024, 1, 1, 12, 0, 0), do=self.work  # we will make the action happen at 12:00 20/8/22
        )  # This is a callback function, defines what to do at this time.
        self.triggers.append(new_trigger)  # Register our trigger

    def work(self, row_data: RowData):
        """
        When time is up, work function will be called.
        """
        pass

Main logic to run Actuator

I think UniV3Pool and Pool (in pool_info) are the same thing so they could be merged and a separate func for getting the pool info could be used

In [4]:
# Declare a token, and it's name will be used as unit of amounts.
usdc = TokenInfo(name="usdc", decimal=6)  # declare token usdc
eth = TokenInfo(name="eth", decimal=18)  # declare token eth
# Declare an Uniswap V3 pool. We will set the parameters according to the real pool on chain.
pool = UniV3Pool(token0=usdc, token1=eth, fee=0.05, quote_token=usdc)

# Declare a market key, which will be used to find the corresponding market in broker
market_key = MarketInfo("uniswap")

In [5]:
# we should connect demeter-fetch and demeter
# how do we know what we already download and what ranges - should be easier to identify so we can smoothly backtest
# what chains are there to choose from?

In [7]:
ChainType?
#show chain types or somehow sync with the data
#updated the docstrings to at least show what is there to choose

Init signature: ChainType(*values)
Docstring:
Enum representing different blockchain networks.

This enum provides a standardized way to refer to various blockchain networks.
Each enum member is a string representing the lowercase name of the network.

Usage:
    - Access a specific chain: ChainType.polygon
    - Get the string value: str(ChainType.polygon) or ChainType.polygon.value
    - Compare with strings: ChainType.ethereum == "ethereum"
    - List all available chains: ChainType.list()

Attributes:
    ethereum (str): Ethereum mainnet
    polygon (str): Polygon (formerly Matic) network
    optimism (str): Optimism L2 network
    arbitrum (str): Arbitrum L2 network
    celo (str): Celo network
    bsc (str): Binance Smart Chain
    base (str): Base network
    avalanche (str): Avalanche network
    fantom (str): Fantom network
    harmony (str): Harmony network
File:           ~/Documents/AMM/demeter/demeter/_typing.py
Type:           EnumType
Subclasses:

In [8]:
print(ChainType.list())

[<ChainType.ethereum: 'ethereum'>, <ChainType.polygon: 'polygon'>, <ChainType.optimism: 'optimism'>, <ChainType.arbitrum: 'arbitrum'>, <ChainType.celo: 'celo'>, <ChainType.bsc: 'bsc'>, <ChainType.base: 'base'>, <ChainType.avalanche: 'avalanche'>, <ChainType.fantom: 'fantom'>, <ChainType.harmony: 'harmony'>]

In [11]:

# Declare the market,
market = UniLpMarket(market_key, pool)  # uni_market:UniLpMarket, positions: 0, total liquidity: 0
# load data for market. those data is prepared by download tool
# we should automatically sync it with fetch one so we can automatically load the data
# and show what date range is available? 
market.data_path = "/Users/gnapsamuel/Documents/AMM/demeter-fetch/sample-data"  # set data path
market.load_data(
    chain=ChainType.ethereum.name,  # load data
    contract_addr="0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640",
    start_date=date(2024, 7, 1),
    end_date=date(2024, 10, 1),
)

# Declare the Actuator, which controls the whole process
actuator = Actuator()  # declare actuator, Demeter Actuator (broker:assets: ; markets: )
# add market to broker
actuator.broker.add_market(market)
# Initial some fund to broker.
actuator.broker.set_balance(usdc, 10000)
actuator.broker.set_balance(eth, 10)
# Set strategy to actuator

10 ETH

In [12]:
actuator.strategy = NoProvisionStrategy()  # set strategy to actuator
# Set price. Those price will be used in all markets.
# Usually, you will have to find the price list from outer source.
# Luckily, uniswap pool data contains price information. So UniLpMarket provides a function to retrieve price list.
actuator.set_price(market.get_price_from_data())
# run test, If you use default parameter, final fund status will be printed in console.

# actuator.run()

Run actuator with evaluators and save result to files

In [15]:
#TypeError: type Timestamp doesn't define __round__ method

In [14]:
actuator.account_status_df

l1                                              net_value tokens       uniswap                                                                                                                      price
l2                                                          USDC ETH net_value base_uncollected quote_uncollected base_in_position quote_in_position position_count                                   ETH USDC
2024-07-01 00:00:00  44343.933168532335355692139287799831  10000  10     0E-31                0                 0                0                 0              0  3434.3933168532335355692139287799831    1
2024-07-01 00:01:00  44347.367561849188589227708501728644  10000  10     0E-31                0                 0                0                 0              0  3434.7367561849188589227708501728644    1
2024-07-01 00:02:00  44343.933168532335355692139287799831  10000  10     0E-31                0                 0                0                 0              0  3434.3933168532335355692139287799831    1
2024-07-01 00:03:00  44343.933168532335355692139287799831  10000  10     0E-31                0                 0                0                 0              0  3434.3933168532335355692139287799831    1
2024-07-01 00:04:00  44340.499118620473308361303157484093  10000  10     0E-31                0                 0                0                 0              0  3434.0499118620473308361303157484093    1
...                                                   ...    ...  ..       ...              ...               ...              ...               ...            ...                                   ...  ...
2024-10-01 23:55:00  34521.302482714785769446849850867194  10000  10     0E-31                0                 0                0                 0              0  2452.1302482714785769446849850867194    1
2024-10-01 23:56:00  34501.694265455760429043679145275127  10000  10     0E-31                0                 0                0                 0              0  2450.1694265455760429043679145275127    1
2024-10-01 23:57:00  34499.244341021658263217357409534168  10000  10     0E-31                0                 0                0                 0              0  2449.9244341021658263217357409534168    1
2024-10-01 23:58:00  34499.244341021658263217357409534168  10000  10     0E-31                0                 0                0                 0              0  2449.9244341021658263217357409534168    1
2024-10-01 23:59:00  34489.447092719784548895138010447659  10000  10     0E-31                0                 0                0                 0              0  2448.9447092719784548895138010447659    1

[133920 rows x 11 columns]

In [13]:
# show me more info on what dates we are going through in the begging
# what strategy are we implementing ? 
actuator.run()
print({k: round(v, 5) for k, v in performance_metrics(
    actuator.account_status_df["net_value"], benchmark=actuator.account_status_df["price"]["ETH"]
).items()})

actuator.save_result(
    path="./result",  # save path
    account=True,  # save account status list as a csv file
    actions=True,  # save actions as a json file and a pickle file
)

2024-10-04 19:17:11,907 - INFO - Qute token is USDC
2024-10-04 19:17:11,908 - INFO - init strategy...
2024-10-04 19:17:11,919 - INFO - start main loop...
100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 133920/133920 [00:11<00:00, 11829.51it/s]
2024-10-04 19:17:23,258 - INFO - main loop finished
2024-10-04 19:17:24,450 - INFO - Print actuator summary
2024-10-04 19:17:24,609 - INFO - Backtesting finished, execute time 12.705981969833374s

Final account status
Token balance in broker
USDC      :10000                    ETH       :10
Position value in markets
uniswap(UniLpMarket)
token0    :USDC                     token1    :ETH                      fee(%)    :0.0500                   quote token:USDC
positions
Empty DataFrame


Quote by: USDC
Account balance history
l1                  net_value tokens       uniswap                                                                                          price
l2                              USDC ETH net_value base_uncollected quote_uncollected base_in_position quote_in_position position_count       ETH USDC
2024-07-01 00:00:00 44343.933  10000  10         0                0                 0                0                 0              0 3434.3933    1
2024-07-01 00:01:00 44347.368  10000  10         0                0                 0                0                 0              0 3434.7368    1
2024-07-01 00:02:00 44343.933  10000  10         0                0                 0                0                 0              0 3434.3933    1
2024-07-01 00:03:00 44343.933  10000  10         0                0                 0                0                 0              0 3434.3933    1
2024-07-01 00:04:00 44340.499  10000  10         0                0                 0                0                 0              0 3434.0499    1
...                       ...    ...  ..       ...              ...               ...              ...               ...            ...       ...  ...
2024-10-01 23:55:00 34521.302  10000  10         0                0                 0                0                 0              0 2452.1302    1
2024-10-01 23:56:00 34501.694  10000  10         0                0                 0                0                 0              0 2450.1694    1
2024-10-01 23:57:00 34499.244  10000  10         0                0                 0                0                 0              0 2449.9244    1
2024-10-01 23:58:00 34499.244  10000  10         0                0                 0                0                 0              0 2449.9244    1
2024-10-01 23:59:00 34489.447  10000  10         0                0                 0                0                 0              0 2448.9447    1

[133920 rows x 11 columns]

TypeError: type Timestamp doesn't define __round__ method